---
name: ⚒️ CI

on:
  pull_request: {}
  push:
    branches:
      - master

env:
  BUNDLE_WITHOUT: release

jobs:
  rubocop_and_matrix:
    runs-on: ubuntu-24.04
    outputs:
      ruby: ${{ steps.ruby.outputs.versions }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.4"
          bundler-cache: true
      - name: Run linter
        run: bundle exec rake rubocop
      - id: ruby
        uses: voxpupuli/ruby-version@v1
  test:
    name: "Ruby ${{ matrix.ruby }}"
    needs: rubocop_and_matrix
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        ruby: ${{ fromJSON(needs.rubocop_and_matrix.outputs.ruby) }}
    steps:
      - uses: actions/checkout@v4
      - name: Install Ruby ${{ matrix.ruby }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Run unit tests
        run: bundle exec rake spec
      - name: Run behavior tests
        run: bundle exec cucumber
        env:
          GIT_COMMITTER_NAME: 'Aruba'
          GIT_COMMITTER_EMAIL: 'aruba@example.com'
          GIT_AUTHOR_NAME: 'Aruba'
          GIT_AUTHOR_EMAIL: 'aruba@example.com'
      - name: Build gem
        run: gem build --strict --verbose *.gemspec
  tests:
    needs:
      - rubocop_and_matrix
      - test
    runs-on: ubuntu-latest
    name: Test suite
    steps:
      - run: echo Test suite completed
